name: Integration Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          template: "test/README.md.tpl"
          writeTo: "test/README.md"

      - name: Check outputs and modified files
        run: |
          cat test/README.md
